# Generated by Django 2.1.2 on 2018-12-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionalCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('leader', models.CharField(max_length=20)),
                ('assistant', models.CharField(blank=True, max_length=30, null=True)),
                ('church_location', models.CharField(max_length=30)),
                ('frontier', models.CharField(max_length=30)),
            ],
        ),
    ]
